version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  